# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cf_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationnote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='модератор'),
        ),
        migrations.CreateModel(
            name='InformationPartner',
            fields=[
            ],
            options={
                'ordering': ('position',),
                'indexes': [],
                'proxy': True,
                'abstract': False,
            },
            bases=('cf_core.partner',),
        ),
        migrations.CreateModel(
            name='RegularPartner',
            fields=[
            ],
            options={
                'ordering': ('position',),
                'indexes': [],
                'proxy': True,
                'abstract': False,
            },
            bases=('cf_core.partner',),
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together=set([('name', 'content_type')]),
        ),
    ]
