# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 08:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cf_core', '0002_auto_20171016_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('position',), 'verbose_name': 'address and contacts', 'verbose_name_plural': 'addressed and contacts'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('position',), 'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='moderationnote',
            options={'ordering': ['-created'], 'verbose_name': 'moderation note', 'verbose_name_plural': 'moderation notes'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('position',), 'verbose_name': 'partner', 'verbose_name_plural': 'partners'},
        ),
        migrations.AlterModelOptions(
            name='servicerule',
            options={'ordering': ('position',), 'verbose_name': 'service rule', 'verbose_name_plural': 'service rules'},
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ('position',), 'verbose_name': 'slider image', 'verbose_name_plural': 'slider images'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ('position',), 'verbose_name': 'social link', 'verbose_name_plural': 'social links'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('position',), 'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(default='', max_length=1024, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lat',
            field=models.FloatField(default=0, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lng',
            field=models.FloatField(default=0, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=526, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='would be used for ordering', verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='would be used for ordering', verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='moderationnote',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='moderationnote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='moderationnote',
            name='is_available',
            field=models.NullBooleanField(choices=[(None, 'wait'), (True, 'allowed'), (False, 'banned')], default=None, verbose_name='is available'),
        ),
        migrations.AlterField(
            model_name='moderationnote',
            name='last_seen',
            field=models.DateTimeField(default=None, null=True, verbose_name='seen time'),
        ),
        migrations.AlterField(
            model_name='moderationnote',
            name='note',
            field=models.TextField(default='', verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='moderationnote',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='object id'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='base_type',
            field=models.CharField(choices=[('regular', 'regular'), ('info', 'info')], default='regular', max_length=16, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='icon',
            field=models.ImageField(upload_to='partners/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='would be used for ordering', verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='servicerule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_rules', to='cf_core.ServiceRule', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='servicerule',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='would be used for ordering', verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='servicerule',
            name='text',
            field=models.CharField(default='', max_length=128, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='crop',
            field=models.BooleanField(default=False, verbose_name='использовать crop'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='height',
            field=models.PositiveIntegerField(default=0, help_text='on 0 does not crop', verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='sliders/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='would be used for ordering', verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='width',
            field=models.PositiveIntegerField(default=0, help_text='on 0 does not crop', verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=easy_thumbnails.fields.ThumbnailerField(upload_to='icons/social/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(choices=[('vk', 'VK'), ('fb', 'Facebook'), ('tw', 'Twitter'), ('gplus', 'Google+'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], default='', max_length=512, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='would be used for ordering', verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='status',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='', max_length=512, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='status',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='would be used for ordering', verbose_name='position'),
        ),
    ]
